//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Id_Employee { get; set; }
        public int Id_Buyer { get; set; }
        public int Id_Car { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Car Car { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
